kind: Pod
apiVersion: v1
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-pod
      image: ubuntu
      command: ["/bin/bash", "-ec", "apt-get update && apt-get install curl dnsutils iputils-* -y; while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Never

